server.port=8081
spring.application.name=auth-service

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${AUTH_DB_USERNAME:naildesigner}
spring.datasource.password=${AUTH_DB_PASSWORD:naildesigner}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret.key=${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=}

app.seed.enabled=${APP_SEED_ENABLED:false}
app.seed.user-password=${APP_SEED_USER_PASSWORD:senhaForte123}
app.seed.admin-password=${APP_SEED_ADMIN_PASSWORD:Admin123!ChangeMe}
app.seed.demo-password=${APP_SEED_DEMO_PASSWORD:Demo123!ChangeMe}

eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
