CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL,
    servico_id BIGINT NOT NULL,
    profissional_id UUID NOT NULL,
    data_hora_inicio TIMESTAMP NOT NULL,
    data_hora_fim TIMESTAMP NOT NULL,
    status VARCHAR(255),
    observacoes VARCHAR(500)
);

CREATE TABLE bloqueio_horario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_bloqueio DATE,
    hora_inicio TIME,
    hora_fim TIME,
    profissional_id UUID,
    motivo VARCHAR(255)
);
