spring.application.name=messaging-service

server.port=8082

resend.api-key=${RESEND_API_KEY:}
resend.base-url=${RESEND_BASE_URL:https://api.resend.com}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}

jwt.secret.key=${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=}
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
