CREATE TABLE servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    preco DOUBLE PRECISION NOT NULL,
    duracao INTEGER NOT NULL
);

CREATE TABLE servico_imagens (
    servico_id BIGINT NOT NULL,
    imagens VARCHAR(255),
    CONSTRAINT fk_servico_imagens_servico
        FOREIGN KEY (servico_id)
        REFERENCES servico (id)
        ON DELETE CASCADE
);
